language: python
matrix:
    include:
        - dist: trusty
          python: 2.7
        - dist: trusty
          python: 3.4
        - dist: trusty
          python: 3.5
        - dist: trusty
          python: 3.5-dev
        - dist: trusty
          python: 3.6
        - dist: trusty
          python: 3.6-dev
        - dist: xenial
          python: 3.7
          sudo: true
        - dist: xenial
          python: 3.7-dev
        - dist: xenial
          python: 3.8-dev
          sudo: true
install:
    - pip install -r requirements.txt
script:
    - py.test --cov=sportsreference --cov-report term-missing tests/
    - pep8 sportsreference/ tests/
